name: "Terraform CI/CD & Security Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  terraform-audit:
    name: "Static Analysis & Security Audit"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # DEBUG STEP: This helps us see exactly where the files are if it fails again
      - name: Debug File Structure
        run: ls -R

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init (Backendless)
        # --- ADD LAB3 PREFIX ---
        run: |
          cd LAB3/env/tokyo
          terraform init -backend=false
          cd ../saopaulo
          terraform init -backend=false

      - name: Terraform Validate (Tokyo)
        run: |
          cd LAB3/env/tokyo
          terraform validate

      - name: Terraform Validate (SÃ£o Paulo)
        run: |
          cd LAB3/env/saopaulo
          terraform validate

      - name: Run Trivy Vulnerability Scanner (IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
